### ISSUE TITLE
怎么私信你？

### ISSUE THREAD

**Issue by DearZack** [key762/abMusic#1]

**Comment by key762** [comment]
直接发机器码出来

**Comment by DearZack** [comment]
=========================================================
=                                                       =
=      Java Class Encryption Tool v1.2.1   by Mr.K      =
=                                                       =
=========================================================

Server code is: 434EEF81CBD4A7A372F7575778F430AED41D8CD98F00B204E9800998ECF8427ED41D8CD98F00B204E9800998ECF8427E

**Comment by DearZack** [comment]
http://127.0.0.1:8088/disst?id=9141251677

![image](https://github.com/key762/abMusic/assets/17618134/a981bddb-468b-4edb-b9b2-e5be3222adf1)
报错了

**Comment by key762** [comment]
![Uploading 截屏2024-02-01 18.37.40.png…]()

**Comment by key762** [comment]
我试了 没问题

**Comment by DearZack** [comment]
方便➕一下qq或者微信吗

**Comment by key762** [comment]
q2940397985
